### ISSUE TITLE
charmap error

### ISSUE THREAD

**Issue by Drac0666** [avalon60/ctk_theme_builder#44]
Hi

After executing 

c:\temp\theme_builder_setup.py -p c:\temp\ctk_theme_builder-3.1.0.zip -i c:\apps

im getting UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 526: character maps to <undefined>
`(base) C:\Windows\system32>python c:\temp\theme_builder_setup.py -p c:\temp\ctk_theme_builder-3.1.0.zip -i c:\apps
Checking Python interpreter version...
Python version, 3.11.5, is a supported version.
Starting CTk Theme Builder deployment.

Operating System: Windows 10.0.19045 10.0.19045
Installation base location: C:\apps
Updating existing application at: C:\apps\ctk_theme_builder

======================== KEY LOCATION MAPPINGS ==========================
Package Location: C:\temp\ctk_theme_builder-3.1.0.zip
App Home = C:\apps\ctk_theme_builder
Assets Location = C:\apps\ctk_theme_builder\assets
User Theme Location = C:\apps\ctk_theme_builder\user_themes
Log Location = C:\apps\ctk_theme_builder\log
=========================================================================

Checking for repository: C:\apps\ctk_theme_builder\assets\data\ctk_theme_builder.db
Repository located - pre-existing installation.
Unpacking package: C:\temp\ctk_theme_builder-3.1.0.zip to: C:\apps
Removing previous: C:\apps\ctk_theme_builder\get-pip.py
Removing previous: C:\apps\ctk_theme_builder\theme_builder_setup.py
Removing previous: C:\apps\ctk_theme_builder\build_app.sh
Removing previous: C:\apps\ctk_theme_builder\ctk_theme_builder.sh
Removing previous: C:\apps\ctk_theme_builder\build_app.bat
Removing previous: C:\apps\ctk_theme_builder\ctk_theme_builder.bat
Removing previous: C:\apps\ctk_theme_builder\view\about.py
Removing previous: C:\apps\ctk_theme_builder\view\control_panel.py
Removing previous: C:\apps\ctk_theme_builder\view\ctk_button_dnd.py
Removing previous: C:\apps\ctk_theme_builder\view\ctk_theme_preview.py
Removing previous: C:\apps\ctk_theme_builder\view\export_import.py
Removing previous: C:\apps\ctk_theme_builder\view\geometry_dialog.py
Removing previous: C:\apps\ctk_theme_builder\view\harmonics_dialog.py
Removing previous: C:\apps\ctk_theme_builder\view\preferences.py
Removing previous: C:\apps\ctk_theme_builder\view\provenance_dialog.py
Removing previous: C:\apps\ctk_theme_builder\view\theme_merger.py
Removing previous: C:\apps\ctk_theme_builder\view\view_utils.py
Removing previous: C:\apps\ctk_theme_builder\view\__init__.py
Removing previous: C:\apps\ctk_theme_builder\controller\ctk_theme_builder.py
Removing previous: C:\apps\ctk_theme_builder\controller\__init__.py
Removing previous: C:\apps\ctk_theme_builder\utils\ctk_theme_builder_qa_app.sh
Removing previous: C:\apps\ctk_theme_builder\utils\freeze.sh
Removing previous: C:\apps\ctk_theme_builder\utils\tb-package.sh
Removing previous: C:\apps\ctk_theme_builder\utils\cbtk_kit.py
Removing previous: C:\apps\ctk_theme_builder\utils\color_constants.py
Removing previous: C:\apps\ctk_theme_builder\utils\ctk_theme_builder_qa_app.py
Removing previous: C:\apps\ctk_theme_builder\utils\ctk_theme_migrate.py
Removing previous: C:\apps\ctk_theme_builder\utils\loggerutl.py
Removing previous: C:\apps\ctk_theme_builder\utils\__init__.py
Inspecting CTk Theme Builder application home directory...
Install base, C:\apps, looks fine.

Launching build_app.bat
Traceback (most recent call last):
  File "c:\temp\theme_builder_setup.py", line 631, in <module>
    lines = [line for line in f]
            ^^^^^^^^^^^^^^^^^^^^
  File "c:\temp\theme_builder_setup.py", line 631, in <listcomp>
    lines = [line for line in f]
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edena\anaconda3\Lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 526: character maps to <undefined>

(base) C:\Windows\system32>
`

**Comment by avalon60** [comment]
Hello @Drac0666.

It looks like you may have an unexpected environment setting. Perhaps the Locale is non Western European? Another possibility may be that it's because you are using Anaconda and Ctk Theme Builder, is developed/tested using standard Python.

You could try:

```
set PYTHONIOENCODING=utf-8
c:\temp\theme_builder_setup.py -p c:\temp\ctk_theme_builder-3.1.0.zip -i c:\apps
```

**Comment by avalon60** [comment]
The installation has been radically changed now and so this is no longer relevant. Please see the [README](https://github.com/avalon60/ctk_theme_builder#) - Closing the issue.
